services:
  user-service:
    image: ht3064/user-service:lgcns
    container_name: user-service
    environment:
      spring.cloud.config.uri: http://config-service:8888
      spring.zipkin.base-url: http://zipkin:9411
      spring.rabbitmq.host: rabbitmq
      eureka.client.service-url.default-zone: http://eureka-service:8761/eureka/
      management.zipkin.tracing.endpoint: http://zipkin:9411/api/v2/spans
    networks:
      my-network:

  order-service:
    image: ht3064/order-service:lgcns
    container_name: order-service
    environment:
      spring.kafka.host: broker
      spring.rabbitmq.host: rabbitmq
      spring.zipkin.base-url: http://zipkin:9411
      spring.datasource.url: jdbc:mariadb://mariadb-server:3306/mydb
      eureka.client.service-url.default-zone: http://eureka-service:8761/eureka/
      management.zipkin.tracing.endpoint: http://zipkin:9411/api/v2/spans
    networks:
      my-network:

  catalog-service:
    image: ht3064/catalog-service:lgcns
    container_name: catalog-service
    environment:
      spring.kafka.host: broker
      spring.datasource.url: jdbc:mariadb://mariadb-server:3306/mydb
      eureka.client.service-url.default-zone: http://eureka-service:8761/eureka/
      management.zipkin.tracing.endpoint: http://zipkin:9411/api/v2/spans
    networks:
      my-network:

networks:
  my-network:
    external: true
    name: ecommerce-network
