server:
  port: 8888

spring:
#  profiles:
#    active: native
  application:
    name: config-service
  cloud:
    config:
      server:
#        native:
#          search-locations: file:///Users/choehyeontae/Documents/msa
        git: #default
          uri: https://github.com/ht3064/spring-cloud-config.git
          default-label: main
#          username: <github-id>
#          password: <gihub-accessToken>
        bootstrap: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, refresh, metrics
