server:
  port: 8888

spring:
#  profiles:
#    active: native
  application:
    name: config-service
  cloud:
    config:
      server:
#        native:
#          search-locations: file:///Users/choehyeontae/Desktop/git/toy-msa-etc/git-local-repo
        git: #default
          uri: https://github.com/joneconsulting/spring-cloud-config
#          uri: https://github.com/ht3064/spring-cloud-config
          default-label: master
#          default-label: main
        #          username: <github-id>
#          password: <gihub-accessToken>
        bootstrap: true
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, refresh, metrics
